title: ST R17 ROS Driver
email: yoonyoung.cho@students.olin.edu
gmail: jchocholate@gmail.com
address: 1000 Olin Way, Needham, Ma
phone: (+1) 213-220-3492
description: > # this means to ignore newlines until "baseurl:"
    ROS Interface for the ST-R17 Robot Arm from ST Robotics
baseurl: "" # the subpath of your site, e.g. /blog
github_username: yycho0108
# Build settings
markdown: kramdown
