st_r17:
    st_r17_controller:
        type: position_controllers/JointTrajectoryController
        action_ns: "follow_joint_trajectory"
        joints:
            - waist
            - shoulder
            - elbow
            - hand
            - wrist
        constraints:
            goal_time: 1.0
            stopped_velocity_tolerance: 0.05
            waist:
                goal: 0.05
            shoulder:
                goal: 0.05
            elbow:
                goal: 0.05
            hand:
                goal: 0.05
            wrist:
                goal: 0.05

    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

controller_list:
  - name: "st_r17/st_r17_controller"
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory 
    default: true
    joints:
        - waist
        - shoulder
        - elbow
        - hand
        - wrist
    constraints:
        goal_time: 1.0
        stopped_velocity_tolerance: 0.05
        waist:
            goal: 0.05
        shoulder:
            goal: 0.05
        elbow:
            goal: 0.05
        hand:
            goal: 0.05
        wrist:
            goal: 0.05
